/**
 * Recovered behavioral spec — equivalent to the audited LLM agent.
 * Generated by Kazdov Spec from observed traces.
 */
export function decision(x: number): number {
  return (((5 * x * x + 7 * x + 3) % 19) + 19) % 19;
}
