/**
 * Recovered behavioral spec — equivalent to the audited LLM agent.
 * Generated by Kazdov Spec from observed traces.
 */
export function decision(x: number): number {
  return (((7 * x * x + 11 * x + 1) % 23) + 23) % 23;
}
