/**
 * Recovered behavioral spec — equivalent to the audited LLM agent.
 * Generated by Kazdov Spec from observed traces.
 */
export function decision(x: number): number {
  // Modular exponentiation a^x mod m via fast exponentiation.
  let result = 1n;
  let base = BigInt(3) % BigInt(19);
  let exp = BigInt(x);
  while (exp > 0n) {
    if (exp & 1n) result = (result * base) % BigInt(19);
    exp >>= 1n;
    base = (base * base) % BigInt(19);
  }
  return Number(result);
}
