// Recovered behavioral spec — equivalent to the audited LLM agent.
// Generated by Kazdov Spec.

pub fn decision(x: u32) -> u64 {
    // Modular exponentiation 3^x mod 19.
    let mut result: u64 = 1;
    let mut base: u64 = (3u64) % (19u64);
    let mut exp = x;
    while exp > 0 {
        if exp & 1 == 1 { result = (result * base) % (19u64); }
        exp >>= 1;
        base = (base * base) % (19u64);
    }
    result
}
