/**
 * Recovered behavioral spec — equivalent to the audited LLM agent.
 * Generated by Kazdov Spec from observed traces.
 */
export function decision(x: number): number {
  return ((7 * x + 4) % 13 + 13) % 13;
}
