/**
 * Recovered behavioral spec — equivalent to the audited LLM agent.
 * Generated by Kazdov Spec from observed traces.
 */
export function decision(x: number): number {
  return ((13 * x + 7) % 17 + 17) % 17;
}
