/**
 * Recovered behavioral spec — equivalent to the audited LLM agent.
 * Generated by Kazdov Spec from observed traces.
 */
export function decision(x: number): number {
  return ((19 * x + 11) % 23 + 23) % 23;
}
